@startuml
Tommy -> Carl : encontrarAuto(marca:String,color:String,capaciad:int)
activate Carl
Carl -> CiudadCarl :getAutos():Collection<Auto>
activate CiudadCarl
CiudadCarl -> Ciudad :getAutos():Collection<Auto>
activate Ciudad
Ciudad --> CiudadCarl :Collection<Auto>
deactivate Ciudad
CiudadCarl --> Carl : Collection<Auto>
deactivate CiudadCarl
collections Auto
loop para cada auto in Collection<Auto>
    Carl -> Auto: getMarca())
    Auto --> Carl: marca
    Carl -> Auto: getColor())
    Auto --> Carl: color
    Carl -> Auto: getCapacidad())
    Auto --> Carl: capacidad
    Carl -> Auto : cumpleEspecificaciones(marca,color,capacidad)
    Auto --> Carl : cumple
    opt cumple
        Carl -> Auto : getPrecio()
        Auto --> Carl : precio
        Carl -> Carl: extraPorPedido
        Carl -> Tommy : puedePagar(precio+extraPorPedido)
        activate Tommy
        Tommy --> Carl : puede
        deactivate Tommy
        opt puede
            Carl --> Tommy :auto
        end
        |||
    end
end

Carl -> Carl : armarEspecial()
Carl -> Carl : color = negro
Carl -> Carl : patente = BAT-MAN-X
note right : X es siempre un numero diferente
Carl -> Carl : capacidad=4
create AutoEspecial
Carl -> AutoEspecial : new Auto(color,patente,capacidad)
AutoEspecial --> Carl: auto
Carl --> Tommy: auto
deactivate Carl


@enduml