@startuml


ParentGameObject -> GameObject : update()
GameObject -> While_1 : update()
    group if condition
    While_1 -> RunnableX : run()
    RunnableX -> ResourceY : use_and_modify()
    RunnableX <<-- ResourceY
    While_1 <<-- RunnableX
    end
GameObject <<-- While_1
GameObject -> While_2 : update()
    group if condition
    While_2 -> RunnableX : run()
    RunnableX -> ResourceY : use_and_modify()
    RunnableX <<-- ResourceY
    While_2 <<-- RunnableX
    end
GameObject <<-- While_2
ParentGameObject <-- GameObject : update()

@enduml
